configuration :
  - name : alice
    ip : 127.0.0.1
    port : 12344  
               
  - name : bob
    ip : 127.0.0.1
    port : 14255
    
  - name : charlie
    ip : 127.0.0.1
    port : 12998
    
  - name : logger
    ip : 127.0.0.1
    port : 1987
    logAllMessages : false


sendRules :
  - action : duplicate
    kind : Ack
  - action : delay 
    kind : HTTP
  - action : drop 
    kind : Lookup
receiveRules :
  - action : delay
    src : daphne

groups :
  - name : Group1
    members :
      - alice
      - bob
      - charlie
  - name : Group2
    members :
    - logger
    - bob
    - charlie
