# Defines which # Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list
configuration :
  - name : alice
    ip : 10.0.1.20
    port : 12344 # This is the incoming port on which MP will listen
                  # May be changed for further communication as usual
  - name : bob
    ip : 10.0.1.20
    port : 14255
    
  - name : charlie
    ip : 10.0.1.8
    port : 12998
    
  - name : daphne
    ip : 10.0.1.8
    port : 1987

  - name : logger
    ip : 10.0.1.8
    port : 15233
    logAllMessages : false


sendRules :
  - action : duplicate # All Ack messages are duplicated
    kind : Ack
  - action : delay  # All HTTP messages are delayed
    kind : HTTP
  - action : drop # Every Lookup message in the system will be dropped
    kind : Lookup
receiveRules :
  - action : drop # 3rd message from Charlie that anyone
    duplicate: true
