configuration :
  - name : alice
    ip : 10.0.1.33
    port : 12344  
    memberOf :
      - Group1
      - Group4
               
  - name : bob
    ip : 10.0.1.33
    port : 14255
    memberOf :
      - Group1
      - Group2
    
  - name : charlie
    ip : 10.0.1.33
    port : 12998
    memberOf :
      - Group2
      - Group4
    
  - name : daphnie
    ip : 10.0.1.34
    port : 1987
    memberOf :
      - Group1
      - Group3
  
  - name : ellen
    ip : 10.0.1.34
    port : 15255
    memberOf :
      - Group1
    
  - name : frank
    ip : 10.0.1.34
    port : 16998
    memberOf :
      - Group3
    
  - name : gus
    ip : 10.0.1.34
    port : 17987
    memberOf :  
      - Group3
      - Group4
      - Group1


sendRules :
  - action : duplicate
    kind : Ack
  - action : delay 
    kind : HTTP
  - action : drop 
    dest : joe
receiveRules :
  - action : drop
    src : joe

groups :
  - name : Group1
    members :
    - alice
    - bob
    - daphnie
    - ellen
    - gus
    - frank
  - name : Group2
    members :
    - charlie
    - bob
  - name : Group3
    members :
    - daphnie
    - frank
    - gus
  - name : Group4
    members :
    - gus
    - alice
    - charlie
